### ISSUE TITLE
Support for Ros2 Humble

### ISSUE THREAD

**Issue by Sudharsan10** [Slamtec/sllidar_ros2#10]

**Comment by ladrians** [comment]
+1 to this request

**Comment by Usimian** [comment]
+1 seconded

**Comment by debanik123** [comment]
+1 third

**Comment by trentatsa** [comment]
+1

**Comment by xiaoc10020015** [comment]
+1

**Comment by xucheng2008** [comment]
+1

**Comment by xiaoc10020015** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，您的来信本人已收到，将尽快给您回复。

**Comment by Wimll** [comment]
Hi everyone, this MR adds support for Humble and works perfectly fine, maybe @xiaoc10020015 can review and merge the pull request?
