### ISSUE TITLE
In ubuntu 22.04 ros2 humble rplidar s2 firmware build error

### ISSUE THREAD

**Issue by debanik123** [Slamtec/sllidar_ros2#12]
In member function ‘virtual u_result rp::net::SocketAddress::getAddressAsString(char*, size_t) const’:
/home/dj/lidar_ws/src/sllidar_ros2/sdk/src/arch/linux/net_socket.cpp:170:15: error: ordered comparison of pointer with integer zero (‘const char*’ and ‘int’)
  170 |     return ans<=0?RESULT_OPERATION_FAIL:RESULT_OK;

**Comment by nbmi** [comment]
Change the "<=" to "!=".

Note: Not successfully tested, I got stuck further downstream in the Humble node build process.

**Comment by deyouslamtec** [comment]
Fixed, please try the latest version
