### ISSUE TITLE
Difference between repo "sllidar_ros2" and "rplidar_ros"

### ISSUE THREAD

**Issue by A1exan10er** [Slamtec/sllidar_ros2#18]
Hello Slamtec,

I'm using your product "RPLIDAR A1M8" and found two repo here, "sllidar_ros2" and "rplidar_ros".
Could you please explain the difference between them?
I'm using ROS 2 Foxy, which repo should I use in this case?

Look forward to your answer!

Best regards,
Alex

**Comment by A1exan10er** [comment]
As I checked on ROS wiki (https://index.ros.org/r/rplidar_ros/), package "**rplidar_ros**" can be used for **ROS 2 and RPLIDAR A1**. Besides, it can run the rplidar **separately without launching "view in the rviz"**, while package "sllidar_ros2" can only "Run sllidar node **and** view in the rviz".

Does it mean if I want to build my own robot using lidar, I should use package "rplidar_ros" instead of "sllidar_ros2"?
If so, the name of "sllidar_ros2" is so confusing. And the link on your official website also points to GitHub repository "sllidar_ros2". It's really confusing and irritating. :(

**Comment by deyouslamtec** [comment]
rplidar_ros is a ROS1 package，sllidar_ros2 is a ROS2 package。But now we have merged sllidar_ros2 into [rplidar_ros](https://github.com/Slamtec/rplidar_ros/tree/ros2)。For ROS 2 Foxy, you can use sllidar_ros2 or [rplidar_ros](https://github.com/Slamtec/rplidar_ros/tree/ros2), they just have different package names
