### ISSUE TITLE
How to solve this problem

### ISSUE THREAD

**Issue by B-D-D** [Slamtec/sllidar_ros2#23]
[ERROR] [launch]: Caught exception in launch (see debug for traceback): __init__() missing 1 required keyword-only argument: 'node_executable'

**Comment by deyouslamtec** [comment]
If you are using a ROS2 distribution before foxy, you need to replace all 'executable' with 'node_executable' in the launch file you are using

**Comment by B-D-D** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
